### ISSUE TITLE
Generate docs using mkdocs

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#12]
We also should include any utilities needed to generate the docs by other projects.

SDK example:

* https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/mkdocs.yml
* https://github.com/frequenz-floss/frequenz-sdk-python/tree/v0.x.x/docs
* https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/.github/workflows/ci.yaml

API (protobuf) docs generation example:

This will generate the docs as a markdown file and put it in the GitHub job step summary, but we can put it in the mkdocs website instead.

```yaml
  gen-docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate documentation
        run: |
          docker run --rm -v $PWD:$PWD pseudomuto/protoc-gen-doc \
            -I $PWD/proto \
            -I $PWD/submodules/api-common-protos \
            -I $PWD/submodules/frequenz-api-common/proto \
            --doc_opt=markdown,gen-docs.md --doc_out=$PWD \
            $(find $PWD/proto -name *.proto)

      - name: Write summary
        run: cat gen-docs.md > $GITHUB_STEP_SUMMARY
```
