### ISSUE TITLE
Add support for `mike` 2

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#173]
### What's needed?

We need to support the new `mike` major version 2.

### Proposed solution

Bump the dependency.

> Deploy aliases using symbolic links by default; this can be configured via --alias-type on the command line or alias_type in the mike MkDocs plugin

We need to update the templates to set:
```yaml
plugins:
  - mike:
      alias_type: redirect
```
