### ISSUE TITLE
Add a protolint checker to the CI

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#32]
Right now we are using a custom command to do a custom download of the `protolint` tool:

```yaml
jobs:
  protolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get protolint
        run: |
          # checksum taken from: https://github.com/yoheimuta/protolint/releases/download/v0.44.0/checksums.txt
          echo "33627c1fd4392edc9363b414651f60692286c27e54424fc535ebb373a47a3004  protolint_0.44.0_Linux_x86_64.tar.gz" > checksum.txt
          curl -LO https://github.com/yoheimuta/protolint/releases/download/v0.44.0/protolint_0.44.0_Linux_x86_64.tar.gz \
          && sha256sum --check checksum.txt \
          && tar xf protolint_0.44.0_Linux_x86_64.tar.gz \
          && chmod +x protolint \
          && sudo mv protolint /usr/local/bin/protolint
      - name: Run protolint
        run: protolint lint proto
```

There are 2 main problems with this approach:

1. dependabot can't check for updates for us
2. We don't get nice comments in PR with the issues it finds

There are (at least) 2 github actions that we can look at to see if they solve these problems more nicely:

* https://github.com/marketplace/actions/run-protolint-with-reviewdog
* https://github.com/marketplace/actions/protolint

If these are not good enough, there is also a pypi package for protolint that could be used at least to get automatic updates:

* https://pypi.org/project/protolint/

**Comment by llucax** [comment]
I just gave both GitHub actions a try and https://github.com/marketplace/actions/run-protolint-with-reviewdog works best and it is maintained by the same author as protolint. It can report linting errors right in the PR as comments.

* https://github.com/frequenz-floss/frequenz-api-common/pull/31#discussion_r1254424389

![example](https://user-images.githubusercontent.com/1031485/251461601-eeeb50bb-4c8a-48df-bdf2-469373455aff.png)

Configuration example:

```yaml
  protolint:
    name: Lint protobuf files with protolint
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: yoheimuta/action-protolint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          protolint_flags: proto/
          protolint_version: "0.45.0"
          reporter: github-check
```

There are other reporter options, we might need to check which works best for both PRs and pushes: https://github.com/reviewdog/reviewdog#reporters
