### ISSUE TITLE
warning: The 'import' key is renamed 'inventories' for the Python handler

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#357]
### What happened?

We are getting the following warning when using `mkdocs` and related tools like `mike`:

> warning: The 'import' key is renamed 'inventories' for the Python handler

### What did you expect instead?

Update the `mkdocs.yml` file to replace:

```yml
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # ...
          import:
```

With:

```yml
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # ...
          inventories:
```

### Extra information

We also need to update the cookiecutter templates and write a migration step in `cookiecutter/migration.py`.
