### ISSUE TITLE
Add a custom dependabot rule for `repo-config`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#366]
This would help to avoid grouping minor `repo-config` updates with other minor updates, as `repo-config` is at v0.x.x still so minor updates have breaking changes and usually need a migration script to be run or templates regenerated.

Here is an example of how this is implemented in another repository that also have dependencies at v0.x.x:

https://github.com/frequenz-floss/frequenz-client-microgrid-python/blob/18287d0cbc54272344f3c0fe291182e26d613d75/.github/dependabot.yml#L22-L45

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    # ...
    groups:
      required:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "frequenz-client-base*"
          - "frequenz-api-microgrid"
      optional:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "frequenz-client-base*"
          - "frequenz-api-microgrid"
      in-devel-patch:
        patterns:
          - "frequenz-client-base*"
          - "frequenz-api-microgrid"
        dependency-type: "production"
        update-types:
          - "patch"
```
