### ISSUE TITLE
Add keyword labeler app

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#4]
Add [https://github.com/ZeWaka/KeywordLabeler] app configuration in `.github/keylabeler.yml`.

For example:

```yml
# KeywordLabeler app configuration. For more information check:
# https://github.com/ZeWaka/KeywordLabeler#readme

# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: true

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  "part:docs": "part:docs"
  "part:tests": "part:tests"
  "part:tooling": "part:tooling"
  "part:❓": "part:❓"
```

* Make sure all the `part:xxx` labels defined in the repo are present.
* Ideally sort the `labelMappings`

SDK example: https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/.github/keylabeler.yml
