### ISSUE TITLE
Improve pytest warning filtering

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#407]
### What's needed?

We need to easily filter out protobuf version **warnings**.

### Proposed solution

```toml
[tool.pytest.ini_options]
addopts = "-vv"
filterwarnings = [
  "error",
  "once::DeprecationWarning",
  "once::PendingDeprecationWarning",
  # We use a raw string (single quote) to avoid the need to escape special
  # chars as this is a regex
  'ignore:Protobuf gencode version .*exactly one major version older.*:UserWarning',
]
```

### Additional context

* https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/181/commits/114af3166191fed7d6248e38cb757a504e2c5a3b#r2104417626
