### ISSUE TITLE
Add PR Labeler

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#5]
### Workflow

Add a `.github/workflow/labeler.yml` workflow:

```yml
name: Pull Request Labeler

# XXX: !!! SECURITY WARNING !!!
# pull_request_target has write access to the repo, and can read secrets. We
# need to audit any external actions executed in this workflow and make sure no
# checked out code is run (not even installing dependencies, as installing
# dependencies usually can execute pre/post-install scripts). We should also
# only use hashes to pick the action to execute (instead of tags or branches).
# For more details read:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on: [pull_request_target]

jobs:
  Label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        # Only use hashes, see the security comment above
        uses: actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e  # 4.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

### Configuration

Configure the workflow creating a `.github/labeler.yml`.

For example:

```yml
# Configuration for the Labeler GitHub action, executed by
# .github/workflows/labeler.yml.
#
# The basic syntax is [label]: [path patterns].
#
# For more details on the configuration please see:
# https://github.com/marketplace/actions/labeler

"part:docs": 
  - "**/*.md"
  - LICENSE

"part:tests":
  - "tests/**"

"part:tooling":
  - ".git*"
  - ".git*/**"
  - "**/*.toml"
  - "**/*.ini"
  - CODEOWNERS
  - MANIFEST.in
  - "*requirements*.txt"
  - setup.py
  - setup.cfg

"part:BLAH":
  - "src/frequenz/BLAH/**"
```

* Ideally make sure all the `part:xxx` labels defined in the repo are present.

SDK Example:
* https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/.github/labeler.yml
* https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/.github/workflows/labeler.yml
