### ISSUE TITLE
Add a session to check proto files with `protolint`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#58]
[`protolint`](https://github.com/yoheimuta/protolint) is a tool to lint protocol buffer files.

We should add a `nox` session that runs `protolint`. One problem with `protolint` is that is not very popular yet, and it doesn't have an easy to install package in all distributions and also no pypi package for it. Because of this, the nox session should not be included in the default sessions, but it should be explicitly used when running the CI.

Here is how `protolint` is currently being used in the CI:

```yaml
jobs:
  protolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get protolint
        run: |
          # checksum taken from: https://github.com/yoheimuta/protolint/releases/download/v0.38.1/checksums.txt
          echo "c1a43f352da6f96f3e60efe33438eaca6148526e6145d9bbd77c40cebc9895a6  protolint_0.38.1_Linux_x86_64.tar.gz" > checksum.txt

          curl -LO https://github.com/yoheimuta/protolint/releases/download/v0.38.1/protolint_0.38.1_Linux_x86_64.tar.gz \
          && sha256sum --check checksum.txt \
          && tar xf protolint_0.38.1_Linux_x86_64.tar.gz \
          && chmod +x protolint \
          && sudo mv protolint /usr/local/bin/protolint

      - name: Run protolint
        run: protolint lint proto
```

There are also a few alternative GitHub actions to use out of the box:

- https://github.com/marketplace/actions/protolint
- https://github.com/marketplace/actions/run-protolint-with-reviewdog
